### ISSUE TITLE
AttributeError: module 'scipy.misc' has no attribute 'imread'

### ISSUE THREAD

**Issue by juliangdz** [yoonlab/PCA-II#1]
This error pops up when i run the python code

**Comment by retupmoc14** [comment]
I think it need to install [Pillow](https://python-pillow.org/) (formerly [PIL)](http://www.pythonware.com/products/pil/). 
How about try this code? 
`sudo pip install pillow`

**Comment by juliangdz** [comment]
Scipy.misc.imread is deprecated . I tried installing Pillow . But still the same error pops up.

**Comment by retupmoc14** [comment]
`get_image(image_path)` just convert the image file to the numpy array.
If you install PIL, try to modify `get_image()` function below code.
```python
from PIL import Image
def get_image(image_path):
    image = Image.open(image_path)
    return np.asarray(image)
```
